[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1
hook_add = 'let g:deoplete#enable_at_startup = 1'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'blueshirts/darcula'

[[plugins]]
repo = 'cespare/vim-toml'
